import React from 'react'

const OkxIcon = () => {
    return (
        <svg
            width="64"
            height="64"
            viewBox="0 0 64 64"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
        >
            <rect
                x="30.8008"
                y="15.5"
                width="4.4"
                height="4.4"
                fill="#EEEEEE"
            />
            <rect
                x="30.8008"
                y="24.3"
                width="4.4"
                height="4.4"
                fill="#EEEEEE"
            />
            <rect
                x="15.4004"
                y="24.3"
                width="4.4"
                height="4.4"
                fill="#EEEEEE"
            />
            <rect
                x="15.4004"
                y="15.5"
                width="4.4"
                height="4.4"
                fill="#EEEEEE"
            />
            <rect
                x="15.4004"
                y="19.9"
                width="4.4"
                height="4.4"
                fill="#EEEEEE"
            />
            <rect y="24.3" width="4.4" height="4.4" fill="#EEEEEE" />
            <rect
                x="4.40039"
                y="24.3"
                width="4.4"
                height="4.4"
                fill="#EEEEEE"
            />
            <rect y="15.5" width="4.4" height="4.4" fill="#EEEEEE" />
            <rect
                x="4.40039"
                y="15.5"
                width="4.4"
                height="4.4"
                fill="#EEEEEE"
            />
            <rect y="19.9" width="4.4" height="4.4" fill="#EEEEEE" />
            <rect
                x="8.80078"
                y="24.3"
                width="4.4"
                height="4.4"
                fill="#EEEEEE"
            />
            <rect
                x="8.80078"
                y="15.5"
                width="4.4"
                height="4.4"
                fill="#EEEEEE"
            />
            <rect
                x="8.80078"
                y="19.9"
                width="4.4"
                height="4.4"
                fill="#EEEEEE"
            />
            <rect
                x="19.8008"
                y="19.9"
                width="4.4"
                height="4.4"
                fill="#EEEEEE"
            />
            <rect
                x="35.1992"
                y="19.9"
                width="4.4"
                height="4.4"
                fill="#EEEEEE"
            />
            <rect
                x="39.5996"
                y="15.5"
                width="4.4"
                height="4.4"
                fill="#EEEEEE"
            />
            <rect
                x="39.5996"
                y="24.3"
                width="4.4"
                height="4.4"
                fill="#EEEEEE"
            />
            <rect
                x="24.1992"
                y="24.3"
                width="4.4"
                height="4.4"
                fill="#EEEEEE"
            />
            <rect
                x="24.1992"
                y="15.5"
                width="4.4"
                height="4.4"
                fill="#EEEEEE"
            />
        </svg>
    )
}

export default OkxIcon
